In [1]:
import pandas as pd

In [9]:
df = pd.read_csv('/content/Fake_Real_Data.csv')

In [10]:
df.head()

                                                Text label
0   Top Trump Surrogate BRUTALLY Stabs Him In The...  Fake
1  U.S. conservative leader optimistic of common ...  Real
2  Trump proposes U.S. tax overhaul, stirs concer...  Real
3   Court Forces Ohio To Allow Millions Of Illega...  Fake
4  Democrats say Trump agrees to work on immigrat...  Real

In [6]:
df['basement'].value_counts()

basement
no     354
yes    191
Name: count, dtype: int64

In [7]:
df['basement'] = df['basement'].map({'yes':1,'no':0})

In [8]:
df['basement'].value_counts()

basement
0    354
1    191
Name: count, dtype: int64

In [13]:
from sklearn.preprocessing import OneHotEncoder

onehot = OneHotEncoder()
encoded_labels = onehot.fit_transform(df[['label']])
print(encoded_labels.toarray())

[[1. 0.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [1. 0.]
 [1. 0.]]

In [14]:
df['label'].head()

0    Fake
1    Real
2    Real
3    Fake
4    Real
Name: label, dtype: object

In [15]:
documents = [
    "The cat sat on the mat.",
    "The dog sat on the log.",
    "Cats and dogs are pets."
]

In [21]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer(ngram_range=(3,3))
X_in = vectorizer.fit_transform(documents)
print(X_in.toarray())
print(vectorizer.get_feature_names_out())

[[0 1 0 0 0 0 1 1 1 0]
 [0 0 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 0 0 0 0]]
['and dogs are' 'cat sat on' 'cats and dogs' 'dog sat on' 'dogs are pets'
 'on the log' 'on the mat' 'sat on the' 'the cat sat' 'the dog sat']

In [22]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfv = TfidfVectorizer()
X_tfv = tfv.fit_transform(documents)
print(X_tfv.toarray())
print(tfv.get_feature_names_out())

[[0.         0.         0.42755362 0.         0.         0.
  0.         0.42755362 0.32516555 0.         0.32516555 0.6503311 ]
 [0.         0.         0.         0.         0.42755362 0.
  0.42755362 0.         0.32516555 0.         0.32516555 0.6503311 ]
 [0.4472136  0.4472136  0.         0.4472136  0.         0.4472136
  0.         0.         0.         0.4472136  0.         0.        ]]
['and' 'are' 'cat' 'cats' 'dog' 'dogs' 'log' 'mat' 'on' 'pets' 'sat' 'the']

In [23]:
X = df['Text']

In [24]:
X_vec = tfv.fit_transform(X)

In [28]:
print(X_vec[7000].toarray())
print(tfv.get_feature_names_out())

[[0.         0.10569449 0.         ... 0.         0.         0.        ]]
['00' '000' '0000' ... 'zzzzaaaacccchhh' 'zzzzzzzzzzzzz' 'émigré']